input_number:
  # Bbls
  bbls_night_temp:
    name: Bbls Night Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  bbls_morning_temp:
    name: Bbls Morning Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  bbls_day_temp:
    name: Bbls Day Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  bbls_evening_temp:
    name: Bbls Evening Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  bbls_delta_temp:
    name: Bbls Delta Temp
    min: 0
    max: 3
    step: 0.2
    mode: box

  # Living
  living_night_temp:
    name: Living Night Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  living_morning_temp:
    name: Living Morning Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  living_day_temp:
    name: Living Day Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  living_evening_temp:
    name: Living Evening Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  living_delta_temp:
    name: Living Delta Temp
    min: 0
    max: 3
    step: 0.2
    mode: box

  # Bedroom
  bedroom_night_temp:
    name: Bedroom Night Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  bedroom_morning_temp:
    name: Bedroom Morning Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  bedroom_day_temp:
    name: Bedroom Day Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  bedroom_evening_temp:
    name: Bedroom Evening Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  bedroom_delta_temp:
    name: Bedroom Delta Temp
    min: 0
    max: 3
    step: 0.2
    mode: box

  # Kitchen
  kitchen_night_temp:
    name: Kitchen Night Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  kitchen_morning_temp:
    name: Kitchen Morning Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  kitchen_day_temp:
    name: Kitchen Day Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  kitchen_evening_temp:
    name: Kitchen Evening Temp
    min: 10
    max: 30
    step: 0.5
    mode: box

  # Balcony
  balcony_night_temp:
    name: Balcony Night Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  balcony_morning_temp:
    name: Balcony Morning Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  balcony_day_temp:
    name: Balcony Day Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  balcony_evening_temp:
    name: Balcony Evening Temp
    min: 10
    max: 30
    step: 0.5
    mode: box
  balcony_delta_temp:
    name: Balcony Delta Temp
    min: 0
    max: 3
    step: 0.2
    mode: box

  # Away mode
  away_temp:
    name: Away Mode Temp
    min: 12
    max: 30
    step: 0.5
    mode: box

  # Day periods
  # --- Bedroom ---
  bedroom_morning_start:
    name: Bedroom Morning Start
    min: 0
    max: 23
    step: 1
    mode: box
    unit_of_measurement: "h"

  bedroom_day_start:
    name: Bedroom Day Start
    min: 0
    max: 23
    step: 1
    mode: box
    unit_of_measurement: "h"

  bedroom_evening_start:
    name: Bedroom Evening Start
    min: 0
    max: 23
    step: 1
    mode: box
    unit_of_measurement: "h"

  bedroom_night_start:
    name: Bedroom Night Start
    min: 0
    max: 23
    step: 1
    mode: box
    unit_of_measurement: "h"

  # --- Living ---
  living_morning_start:
    name: Living Morning Start
    min: 0
    max: 23
    step: 1
    mode: box
    unit_of_measurement: "h"

  living_day_start:
    name: Living Day Start
    min: 0
    max: 23
    step: 1
    mode: box
    unit_of_measurement: "h"

  living_evening_start:
    name: Living Evening Start
    min: 0
    max: 23
    step: 1
    mode: box
    unit_of_measurement: "h"

  living_night_start:
    name: Living Night Start
    min: 0
    max: 23
    step: 1
    mode: box
    unit_of_measurement: "h"

  # --- Bbls ---
  bbls_morning_start:
    name: Bbls Morning Start
    min: 0
    max: 23
    step: 1
    mode: box
    unit_of_measurement: "h"

  bbls_day_start:
    name: Bbls Day Start
    min: 0
    max: 23
    step: 1
    mode: box
    unit_of_measurement: "h"

  bbls_evening_start:
    name: Bbls Evening Start
    min: 0
    max: 23
    step: 1
    mode: box
    unit_of_measurement: "h"

  bbls_night_start:
    name: Bbls Night Start
    min: 0
    max: 23
    step: 1
    mode: box
    unit_of_measurement: "h"

input_boolean:
  summer_mode:
    name: Summer Mode
  we_are_away:
    name: We Are Away
  living_heater_needed:
    name: Living Heater Needed
  bedroom_heater_needed:
    name: Bedroom Heater Needed
  bbls_heater_needed:
    name: Bbls Heater Needed
  balcony_heater_needed:
    name: Balcony Heater Needed
